/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/topics/{topicId}/questions/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Сгенерировать вопросы по единому тексту темы
         * @description Текст делится на фрагменты, по каждому AI предлагает вопросы. Выполняется асинхронно.
         */
        post: operations["generateQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** Вопросы темы */
        get: operations["listQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Изменить формулировку вопроса */
        patch: operations["updateQuestion"];
        trace?: never;
    };
    "/api/questions/{questionId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Изучать вопрос */
        post: operations["approveQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/{questionId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Не изучать вопрос */
        post: operations["rejectQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/questions/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Массово одобрить или отклонить вопросы */
        post: operations["decideQuestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/cards/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Создать карточки по одобренным вопросам */
        post: operations["generateCards"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/vocabulary/generate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Составить карточки английских слов по тексту
         * @description AI выбирает из текста слова или выражения по инструкции («слова, выделенные жирным», «коллокации»)
         *     и сразу составляет карточки: на лицевой стороне — объяснение на простом английском (B1) и предложение
         *     с пропуском, на оборотной — само выражение, русский перевод и перевод предложения.
         *     Работает и для темы без материалов. Выполняется асинхронно.
         */
        post: operations["generateVocabulary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** Все карточки темы */
        get: operations["listCards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        /** Карточка */
        get: operations["getCard"];
        put?: never;
        post?: never;
        /** Удалить карточку */
        delete: operations["deleteCard"];
        options?: never;
        head?: never;
        /** Изменить вопрос или ответ карточки */
        patch: operations["updateCard"];
        trace?: never;
    };
    "/api/generation-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        /** Статус задачи генерации (для опроса) */
        get: operations["getGenerationJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        QuestionStatus: "GENERATED" | "APPROVED" | "REJECTED" | "CARD_CREATED";
        /** @enum {string} */
        QuestionDecision: "APPROVE" | "REJECT";
        /** @enum {string} */
        GenerationJobType: "QUESTIONS" | "CARDS" | "VOCABULARY";
        /** @enum {string} */
        GenerationJobStatus: "PROCESSING" | "READY" | "ERROR";
        GenerationJobDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string;
            type: components["schemas"]["GenerationJobType"];
            status: components["schemas"]["GenerationJobStatus"];
            /** @description Сколько вопросов или карточек создано */
            itemsCreated: number;
            errorMessage?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string;
        };
        QuestionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string;
            /**
             * Format: uuid
             * @description Фрагмент единого текста, по которому создан вопрос
             */
            chunkId?: string;
            text: string;
            /** @description Цитата из материала, на которой основан вопрос */
            sourceFragment?: string;
            status: components["schemas"]["QuestionStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        UpdateQuestionRequest: {
            text: string;
        };
        QuestionDecisionRequest: {
            questionIds: string[];
            decision: components["schemas"]["QuestionDecision"];
        };
        FlashcardDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string;
            /** Format: uuid */
            questionId?: string;
            front: string;
            back: string;
            sourceFragment?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GenerateVocabularyRequest: {
            /** @description Слова, список или текст; выделение жирным — `**слово**` */
            text: string;
            /** @description Что взять из текста, например «слова, выделенные жирным» или «коллокации»; пусто — все слова */
            instruction?: string;
        };
        /** @description Передаются только изменяемые поля */
        UpdateCardRequest: {
            front?: string;
            back?: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: {
        /** @description Некорректный запрос (VALIDATION_FAILED, MALFORMED_REQUEST) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Нет валидного токена (UNAUTHORIZED) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не найдено (QUESTION_NOT_FOUND, CARD_NOT_FOUND, GENERATION_JOB_NOT_FOUND) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description По вопросу уже создана карточка (QUESTION_ALREADY_HAS_CARD) */
        QuestionConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        TopicId: string;
        QuestionId: string;
        CardId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generateQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задача генерации запущена */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Текст темы ещё не готов (TOPIC_CONTENT_NOT_READY) или генерация уже идёт (GENERATION_IN_PROGRESS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listQuestions: {
        parameters: {
            query?: {
                status?: components["schemas"]["QuestionStatus"];
            };
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вопросы в порядке появления */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateQuestionRequest"];
            };
        };
        responses: {
            /** @description Обновлённый вопрос */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["QuestionConflict"];
        };
    };
    approveQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вопрос одобрен */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["QuestionConflict"];
        };
    };
    rejectQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: components["parameters"]["QuestionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вопрос отклонён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["QuestionConflict"];
        };
    };
    decideQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionDecisionRequest"];
            };
        };
        responses: {
            /** @description Изменённые вопросы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuestionDto"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["QuestionConflict"];
        };
    };
    generateCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задача генерации запущена */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Нет одобренных вопросов (NO_APPROVED_QUESTIONS) или генерация уже идёт (GENERATION_IN_PROGRESS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generateVocabulary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateVocabularyRequest"];
            };
        };
        responses: {
            /** @description Задача генерации запущена */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Темы нет или она чужая (TOPIC_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Составление карточек слов по теме уже идёт (GENERATION_IN_PROGRESS) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listCards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточки в порядке создания */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточка удалена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: components["parameters"]["CardId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCardRequest"];
            };
        };
        responses: {
            /** @description Обновлённая карточка */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getGenerationJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задача */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationJobDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
