/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Темы текущего пользователя */
        get: operations["listTopics"];
        put?: never;
        /** Создать тему */
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** Тема по идентификатору */
        get: operations["getTopic"];
        put?: never;
        post?: never;
        /**
         * Удалить тему со всеми материалами
         * @description Вопросы, карточки и прогресс темы удаляются другими модулями по событию TopicDeleted.
         */
        delete: operations["deleteTopic"];
        options?: never;
        head?: never;
        /** Изменить название или описание темы */
        patch: operations["updateTopic"];
        trace?: never;
    };
    "/api/topics/{topicId}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** Источники темы */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/sources/text": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Добавить текст или список слов
         * @description Текст сохраняется без изменений в originalText, обработка идёт асинхронно.
         */
        post: operations["addTextSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/sources/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузить PDF
         * @description Файл сохраняется в хранилище, текст извлекается асинхронно (без OCR).
         */
        post: operations["addPdfSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/sources/youtube": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Добавить видео YouTube
         * @description Backend асинхронно пытается получить субтитры видео.
         */
        post: operations["addYoutubeSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        /** Источник по идентификатору (для опроса статуса) */
        get: operations["getSource"];
        put?: never;
        post?: never;
        /**
         * Удалить источник
         * @description Единый текст темы пересобирается без этого источника.
         */
        delete: operations["deleteSource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{sourceId}/text": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        /** Исходный и извлечённый текст источника */
        get: operations["getSourceText"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** Актуальный единый текст темы */
        get: operations["getTopicContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description DRAFT — нет источников, PROCESSING — идёт обработка, READY — есть готовый текст, ERROR — ни один источник не обработан
         * @enum {string}
         */
        TopicStatus: "DRAFT" | "PROCESSING" | "READY" | "ERROR";
        /** @enum {string} */
        SourceType: "PDF" | "YOUTUBE" | "TEXT" | "WORD_LIST";
        /** @enum {string} */
        TextSourceType: "TEXT" | "WORD_LIST";
        /** @enum {string} */
        SourceStatus: "UPLOADED" | "PROCESSING" | "READY" | "ERROR";
        CreateTopicRequest: {
            /** @example Spring Security */
            title: string;
            description?: string;
        };
        /** @description Передаются только изменяемые поля */
        UpdateTopicRequest: {
            title?: string;
            description?: string;
        };
        TopicDto: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string;
            status: components["schemas"]["TopicStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TextSourceRequest: {
            type?: components["schemas"]["TextSourceType"];
            name?: string;
            text: string;
        };
        YoutubeSourceRequest: {
            /** @example https://www.youtube.com/watch?v=dQw4w9WgXcQ */
            url: string;
            name?: string;
        };
        SourceDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string;
            type: components["schemas"]["SourceType"];
            status: components["schemas"]["SourceStatus"];
            originalName?: string;
            originalUrl?: string;
            /** @description TEXT_EXTRACTION_FAILED, TRANSCRIPT_UNAVAILABLE, SOURCE_PROCESSING_FAILED */
            errorCode?: string;
            errorMessage?: string;
            /** @description Длина извлечённого текста в символах */
            extractedTextLength?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SourceTextDto: {
            /** Format: uuid */
            sourceId: string;
            /** @description Исходный текст (для TEXT и WORD_LIST), никогда не меняется */
            originalText?: string;
            /** @description Текст после извлечения и технической очистки */
            extractedText?: string;
        };
        TopicContentDto: {
            /** Format: uuid */
            topicId: string;
            version: number;
            content: string;
            /** Format: date-time */
            createdAt: string;
        };
        ErrorResponse: {
            code: string;
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: {
        /** @description Некорректный запрос (VALIDATION_FAILED, MALFORMED_REQUEST, UNSUPPORTED_FILE_TYPE, INVALID_YOUTUBE_URL) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Нет валидного токена (UNAUTHORIZED) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не найдено (TOPIC_NOT_FOUND, SOURCE_NOT_FOUND, TOPIC_CONTENT_NOT_FOUND) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        TopicId: string;
        SourceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список тем, новые сверху */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopicRequest"];
            };
        };
        responses: {
            /** @description Тема создана в статусе DRAFT */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тема */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тема удалена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTopicRequest"];
            };
        };
        responses: {
            /** @description Обновлённая тема */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Источники в порядке добавления */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDto"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addTextSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TextSourceRequest"];
            };
        };
        responses: {
            /** @description Источник принят в обработку */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addPdfSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Файл принят в обработку */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Файл больше допустимого размера (FILE_TOO_LARGE) */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addYoutubeSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["YoutubeSourceRequest"];
            };
        };
        responses: {
            /** @description Видео принято в обработку */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Источник */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Источник удалён */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSourceText: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тексты источника */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTextDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTopicContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Последняя версия единого текста */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicContentDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
