import { useEffect, useState } from 'react'
import { Link, NavLink, Navigate, Outlet, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { BookOpen, Check, ChevronLeft, ChevronRight, CircleHelp, FileText, Flame, GraduationCap, LayoutDashboard, LogOut, Menu, Play, Plus, Search, Sparkles, Trash2, Upload, Youtube, X } from 'lucide-react'
import * as authApi from './api/auth'
import * as topicsApi from './api/topics'
import * as sourceApi from './api/sources'
import * as deckApi from './api/deck'
import * as learningApi from './api/learning'
import { useAuth, useLearning, useToast } from './store'
import type { DueCard, Flashcard, Question, Source, Topic } from './types'
import { formatPercent, plural } from './utils'

export function App() {
  const { user, setUser, logout } = useAuth()
  const [booting, setBooting] = useState(Boolean(localStorage.getItem('pamytno-token')))
  useEffect(() => {
    const onUnauthorized = () => { logout(); setBooting(false) }
    window.addEventListener('pamytno:unauthorized', onUnauthorized)
    if (booting) authApi.getCurrentUser().then(setUser).catch(logout).finally(() => setBooting(false))
    return () => window.removeEventListener('pamytno:unauthorized', onUnauthorized)
  }, []) // auth bootstrap is intentionally performed once
  if (booting) return <div className="page-loader"><div className="spinner" /> Загружаем Памятно…</div>
  return <Routes>
    <Route path="/login" element={user ? <Navigate to="/" replace /> : <AuthPage />} />
    <Route path="/register" element={user ? <Navigate to="/" replace /> : <AuthPage register />} />
    <Route element={user ? <AppShell /> : <Navigate to="/login" replace />}>
      <Route path="/" element={<DashboardPage />} />
      <Route path="/topics/new" element={<CreateTopicPage />} />
      <Route path="/topics/:topicId" element={<TopicShell />}>
        <Route index element={<MaterialsPage />} />
        <Route path="materials" element={<MaterialsPage />} />
        <Route path="questions" element={<QuestionsPage />} />
        <Route path="cards" element={<CardsPage />} />
        <Route path="learn" element={<LearningPage />} />
        <Route path="progress" element={<ProgressPage />} />
      </Route>
      <Route path="*" element={<Navigate to="/" replace />} />
    </Route>
  </Routes>
}

function AppShell() {
  const { user, logout } = useAuth()
  const [mobileOpen, setMobileOpen] = useState(false)
  return <div className="app-shell">
    <aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}>
      <div className="brand"><span className="brand-mark">п</span><span>памятно</span></div>
      <nav className="main-nav">
        <NavLink to="/" end onClick={() => setMobileOpen(false)}><LayoutDashboard size={18} /> Обзор</NavLink>
        <NavLink to="/topics/new" onClick={() => setMobileOpen(false)}><Plus size={18} /> Новая тема</NavLink>
      </nav>
      <div className="sidebar-bottom">
        <div className="user-chip"><span className="avatar">{user?.email.slice(0, 1).toUpperCase()}</span><span className="user-email">{user?.email}</span></div>
        <button className="sidebar-logout" onClick={logout}><LogOut size={16} /> Выйти</button>
      </div>
    </aside>
    {mobileOpen && <button className="mobile-backdrop" aria-label="Закрыть меню" onClick={() => setMobileOpen(false)} />}
    <main className="main-content"><button className="mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={22} /></button><Outlet /></main><ToastContainer />
  </div>
}

function AuthPage({ register = false }: { register?: boolean }) {
  const navigate = useNavigate(); const setUser = useAuth((state) => state.setUser)
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  const mutation = useMutation({ mutationFn: () => register ? authApi.register(email, password) : authApi.login(email, password), onSuccess: async (token) => { localStorage.setItem('pamytno-token', token.accessToken); setUser(await authApi.getCurrentUser()); navigate('/') }, onError: (e: Error) => setError(e.message) })
  return <div className="auth-page"><div className="auth-card">
    <div className="brand brand-centered"><span className="brand-mark">п</span><span>памятно</span></div>
    <div className="eyebrow">Личные знания, без шума</div><h1>{register ? 'Создайте свой ритм обучения' : 'С возвращением'}</h1>
    <p className="muted">{register ? 'Собирайте материалы и превращайте их в карточки.' : 'Войдите, чтобы продолжить изучение.'}</p>
    {error && <InlineError message={error} />}
    <form onSubmit={(e) => { e.preventDefault(); setError(''); mutation.mutate() }} className="form-stack">
      <label>Электронная почта<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoFocus /></label>
      <label>Пароль<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={8} required /></label>
      <button className="button button-primary button-wide" disabled={mutation.isPending}>{mutation.isPending ? 'Подождите…' : register ? 'Зарегистрироваться' : 'Войти'}</button>
    </form>
    <p className="auth-switch">{register ? 'Уже есть аккаунт?' : 'Впервые здесь?'} <Link to={register ? '/login' : '/register'}>{register ? 'Войти' : 'Создать аккаунт'}</Link></p>
  </div></div>
}

function DashboardPage() {
  const navigate = useNavigate(); const query = useQuery({ queryKey: ['dashboard'], queryFn: learningApi.getDashboard }); const topics = useQuery({ queryKey: ['topics'], queryFn: topicsApi.listTopics })
  const progressById = new Map((query.data?.topics || []).map((item) => [item.topicId, item]))
  if (query.isLoading || topics.isLoading) return <PageLoading />
  if (query.isError || topics.isError) return <ErrorState onRetry={() => { query.refetch(); topics.refetch() }} />
  const dueToday = query.data?.dueToday ?? 0
  return <div className="content-wrap"><header className="page-header"><div><div className="eyebrow">Твой обзор</div><h1>Что изучим сегодня?</h1><p className="muted">Небольшие шаги складываются в устойчивые знания.</p></div><button className="button button-primary" onClick={() => navigate('/topics/new')}><Plus size={17} /> Новая тема</button></header>
    <section className="today-card"><div className="today-icon"><Flame size={24} /></div><div><span className="eyebrow">Сегодня</span><h2>{dueToday} {plural(dueToday, 'карточка', 'карточки', 'карточек')} к повторению</h2><p className="muted">{dueToday ? 'Самое время освежить то, что уже начинали.' : 'Отлично — на сегодня всё чисто.'}</p></div>{dueToday > 0 && <button className="button button-dark" onClick={() => { const first = topics.data?.find((topic) => (progressById.get(topic.id)?.dueToday || 0) > 0); if (first) navigate(`/topics/${first.id}/learn`) }}>Начать <ChevronRight size={17} /></button>}</section>
    <div className="section-heading"><div><h2>Мои темы</h2><p className="muted">{topics.data?.length || 0} {plural(topics.data?.length || 0, 'тема', 'темы', 'тем')}</p></div></div>
    {!topics.data?.length ? <EmptyState icon={<BookOpen size={24} />} title="Здесь пока пусто" text="Создайте первую тему — добавьте материал, а Памятно поможет выделить главное." action={<button className="button button-primary" onClick={() => navigate('/topics/new')}><Plus size={17} /> Создать тему</button>} /> : <div className="topic-grid">{topics.data.map((topic) => <TopicCard key={topic.id} topic={topic} progress={progressById.get(topic.id)} />)}</div>}
  </div>
}

function TopicCard({ topic, progress }: { topic: Topic; progress?: { progress: number; totalCards: number; dueToday: number; masteredCards: number } }) {
  const navigate = useNavigate(); const percent = progress?.progress || 0
  return <article className="topic-card" onClick={() => navigate(`/topics/${topic.id}`)}><div className="topic-card-top"><span className={`status-dot status-${topic.status.toLowerCase()}`} /> <span className="muted small">{statusLabel(topic.status)}</span><ChevronRight size={18} className="topic-arrow" /></div><h3>{topic.title}</h3>{topic.description && <p className="muted clamp">{topic.description}</p>}<div className="progress-row"><strong>{formatPercent(percent)}</strong><span className="muted">{progress?.totalCards || 0} карточек</span></div><div className="progress-track"><span style={{ width: `${Math.min(percent, 100)}%` }} /></div><div className="topic-card-foot"><span>{progress?.dueToday || 0} повторить сегодня</span><button className="text-button" onClick={(e) => { e.stopPropagation(); navigate(`/topics/${topic.id}/learn`) }}>Продолжить <ChevronRight size={15} /></button></div></article>
}

function CreateTopicPage() {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [error, setError] = useState('')
  const mutation = useMutation({ mutationFn: () => topicsApi.createTopic(title.trim(), description.trim()), onSuccess: async (topic) => { await queryClient.invalidateQueries({ queryKey: ['topics'] }); navigate(`/topics/${topic.id}`) }, onError: (e: Error) => setError(e.message) })
  return <div className="content-wrap narrow"><button className="back-link" onClick={() => navigate(-1)}><ChevronLeft size={17} /> Назад</button><div className="form-page"><div className="eyebrow">Новая тема</div><h1>С чего начнём?</h1><p className="muted intro">Создайте пространство для материала, который хотите запомнить.</p>{error && <InlineError message={error} />}<form className="form-stack" onSubmit={(e) => { e.preventDefault(); setError(''); mutation.mutate() }}><label>Название темы<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Например, Spring Security" maxLength={200} autoFocus required /></label><label>Описание <span className="optional">необязательно</span><textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="О чём эта тема?" rows={4} maxLength={2000} /></label><button className="button button-primary" disabled={mutation.isPending}>{mutation.isPending ? 'Создаём…' : 'Создать тему'} <ChevronRight size={17} /></button></form></div></div>
}

function TopicShell() {
  const { topicId } = useParams(); const query = useQuery({ queryKey: ['topic', topicId], queryFn: () => topicsApi.getTopic(topicId!), enabled: Boolean(topicId) }); const progress = useQuery({ queryKey: ['progress', topicId], queryFn: () => learningApi.getTopicProgress(topicId!), enabled: Boolean(topicId) }); const [showEdit, setShowEdit] = useState(false)
  if (query.isLoading) return <PageLoading />; if (query.isError || !query.data) return <ErrorState />
  const topic = query.data
  return <div className="content-wrap topic-wrap"><div className="topic-breadcrumb"><Link to="/">Обзор</Link><ChevronRight size={14} /> <span>{topic.title}</span></div><header className="topic-header"><div><div className="eyebrow">Тема</div><h1>{topic.title}</h1>{topic.description && <p className="muted">{topic.description}</p>}</div><div className="topic-header-actions"><Link className="button button-primary" to={`/topics/${topic.id}/learn`}><Play size={16} fill="currentColor" /> Учить</Link><button className="icon-button" title="Изменить тему" onClick={() => setShowEdit(true)}>…</button></div></header><div className="topic-stats"><Stat label="Прогресс" value={formatPercent(progress.data?.progress || 0)} /><Stat label="Карточек" value={String(progress.data?.totalCards || 0)} /><Stat label="Повторить сегодня" value={String(progress.data?.dueToday || 0)} accent /></div><nav className="topic-tabs"><TopicTab to="materials" label="Материалы" icon={<FileText size={16} />} /><TopicTab to="questions" label="Вопросы" icon={<CircleHelp size={16} />} /><TopicTab to="cards" label="Карточки" icon={<BookOpen size={16} />} /><TopicTab to="progress" label="Прогресс" icon={<GraduationCap size={16} />} /></nav><Outlet />{showEdit && <EditTopicModal topic={topic} close={() => setShowEdit(false)} />}</div>
}

function TopicTab({ to, label, icon }: { to: string; label: string; icon: React.ReactNode }) { return <NavLink to={to}>{icon}{label}</NavLink> }
function Stat({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className="stat"><span className="muted small">{label}</span><strong className={accent ? 'accent-text' : ''}>{value}</strong></div> }

function MaterialsPage() {
  const { topicId } = useParams(); const queryClient = useQueryClient(); const [modal, setModal] = useState(false); const [contentOpen, setContentOpen] = useState(false)
  const sources = useQuery({ queryKey: ['sources', topicId], queryFn: () => sourceApi.listSources(topicId!), enabled: Boolean(topicId), refetchInterval: (query) => query.state.data?.some((item) => item.status === 'UPLOADED' || item.status === 'PROCESSING') ? 1500 : false })
  const content = useQuery({ queryKey: ['content', topicId], queryFn: () => sourceApi.getTopicContent(topicId!), enabled: contentOpen && Boolean(topicId) })
  const deleteMutation = useMutation({ mutationFn: sourceApi.deleteSource, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['sources', topicId] }) })
  const hasReady = sources.data?.some((source) => source.status === 'READY')
  return <section className="topic-section"><div className="section-heading"><div><h2>Материалы</h2><p className="muted">Соберите всё, что помогает разобраться в теме.</p></div><button className="button button-primary" onClick={() => setModal(true)}><Plus size={17} /> Добавить материал</button></div>{sources.isLoading ? <InlineLoading /> : sources.isError ? <ErrorState onRetry={() => sources.refetch()} /> : !sources.data?.length ? <EmptyState icon={<FileText size={24} />} title="Добавьте первый материал" text="Подойдёт PDF, ссылка на YouTube или собственные заметки." action={<button className="button button-primary" onClick={() => setModal(true)}><Upload size={17} /> Добавить материал</button>} /> : <div className="source-list">{sources.data.map((source) => <SourceRow key={source.id} source={source} onDelete={() => { if (window.confirm('Удалить этот материал?')) deleteMutation.mutate(source.id) }} />)}</div>}{hasReady && <div className="master-text-card"><div><span className="eyebrow">Единый текст темы</span><h3>Все материалы собраны в одном месте</h3><p className="muted">Откройте исходный текст или переходите к созданию вопросов.</p></div><button className="button button-secondary" onClick={() => setContentOpen(true)}>Открыть текст</button></div>}{contentOpen && <Modal title="Исходный текст" close={() => setContentOpen(false)} wide><div className="content-reader">{content.isLoading ? <InlineLoading /> : content.isError ? <InlineError message="Единый текст ещё не готов. Попробуйте чуть позже." /> : <><div className="reader-meta">Версия {content.data?.version} · {content.data?.content.length.toLocaleString('ru-RU')} символов</div><p>{content.data?.content}</p></>}</div></Modal>}{modal && <AddMaterialModal topicId={topicId!} close={() => setModal(false)} />}</section>
}

function SourceRow({ source, onDelete }: { source: Source; onDelete: () => void }) {
  const icon = source.type === 'PDF' ? <FileText size={20} /> : source.type === 'YOUTUBE' ? <Youtube size={20} /> : <BookOpen size={20} />
  return <article className="source-row"><div className={`source-icon source-${source.type.toLowerCase()}`}>{icon}</div><div className="source-main"><div className="source-title">{source.originalName || source.originalUrl || source.type}</div><div className="source-subtitle">{source.type === 'YOUTUBE' && source.originalUrl ? source.originalUrl : sourceTypeLabel(source.type)}{source.extractedTextLength ? ` · ${source.extractedTextLength.toLocaleString('ru-RU')} знаков` : ''}</div>{source.status === 'ERROR' && <div className="source-error">{source.errorMessage || 'Не удалось обработать материал.'}</div>}</div><div className={`source-status source-status-${source.status.toLowerCase()}`}>{source.status === 'READY' ? <><Check size={14} /> Готово</> : source.status === 'ERROR' ? 'Ошибка' : <><span className="mini-spinner" /> Обрабатываем</>}</div><button className="icon-button subtle" onClick={onDelete} title="Удалить материал"><Trash2 size={16} /></button></article>
}

function AddMaterialModal({ topicId, close }: { topicId: string; close: () => void }) {
  const queryClient = useQueryClient(); const showToast = useToast((state) => state.show); const [kind, setKind] = useState<'TEXT' | 'WORD_LIST' | 'YOUTUBE' | 'PDF'>('TEXT'); const [name, setName] = useState(''); const [text, setText] = useState(''); const [url, setUrl] = useState(''); const [file, setFile] = useState<File>(); const [error, setError] = useState('')
  const mutation = useMutation({ mutationFn: () => kind === 'PDF' ? file ? sourceApi.addPdfSource(topicId, file, name) : Promise.reject(new Error('Выберите PDF-файл')) : kind === 'YOUTUBE' ? sourceApi.addYoutubeSource(topicId, { url, name: name || undefined }) : sourceApi.addTextSource(topicId, { type: kind, name: name || (kind === 'WORD_LIST' ? 'Список слов' : 'Мои заметки'), text }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['sources', topicId] }); queryClient.invalidateQueries({ queryKey: ['topic', topicId] }); showToast('Материал добавлен'); close() }, onError: (e: Error) => setError(e.message) })
  return <Modal title="Добавить материал" close={close}><div className="material-types">{([['TEXT', 'Текст', <FileText size={18} />], ['WORD_LIST', 'Слова', <BookOpen size={18} />], ['YOUTUBE', 'YouTube', <Youtube size={18} />], ['PDF', 'PDF', <Upload size={18} />] ] as const).map(([value, label, icon]) => <button key={value} className={kind === value ? 'material-type active' : 'material-type'} onClick={() => setKind(value)}>{icon}{label}</button>)}</div>{error && <InlineError message={error} />}{kind === 'YOUTUBE' ? <div className="form-stack"><label>YouTube URL<input value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://www.youtube.com/watch?v=…" required /></label><label>Название <span className="optional">необязательно</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Название видео" /></label></div> : kind === 'PDF' ? <div className="form-stack"><label>PDF-файл<div className="dropzone"><input type="file" accept="application/pdf,.pdf" onChange={(e) => setFile(e.target.files?.[0])} />{file ? <><Check size={24} /><strong>{file.name}</strong><span className="muted">Файл выбран</span></> : <><Upload size={24} /><strong>Перетащите PDF сюда</strong><span className="muted">или выберите файл</span></>}</div></label><label>Название <span className="optional">необязательно</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Название файла" /></label></div> : <div className="form-stack"><label>{kind === 'WORD_LIST' ? 'Список слов' : 'Текст заметок'}<textarea value={text} onChange={(e) => setText(e.target.value)} rows={9} placeholder={kind === 'WORD_LIST' ? 'optimistic locking\nMVCC\npessimistic locking' : 'Вставьте сюда материал…'} required /></label><label>Название <span className="optional">необязательно</span><input value={name} onChange={(e) => setName(e.target.value)} placeholder={kind === 'WORD_LIST' ? 'Термины' : 'Мои заметки'} /></label></div>}<div className="modal-actions"><button className="button button-secondary" onClick={close}>Отмена</button><button className="button button-primary" disabled={mutation.isPending || (kind === 'PDF' ? !file : kind === 'YOUTUBE' ? !url : !text.trim())} onClick={() => { setError(''); mutation.mutate() }}>{mutation.isPending ? 'Добавляем…' : 'Добавить материал'}</button></div></Modal>
}

function QuestionsPage() {
  const { topicId } = useParams(); const queryClient = useQueryClient(); const navigate = useNavigate(); const [view, setView] = useState<'review' | 'list'>('review'); const [selected, setSelected] = useState<string[]>([]); const [jobId, setJobId] = useState<string>(); const [cardJobId, setCardJobId] = useState<string>(); const [index] = useState(0); const [error, setError] = useState('')
  const questions = useQuery({ queryKey: ['questions', topicId], queryFn: () => deckApi.listQuestions(topicId!), enabled: Boolean(topicId) }); const job = useQuery({ queryKey: ['job', jobId], queryFn: () => deckApi.getGenerationJob(jobId!), enabled: Boolean(jobId), refetchInterval: 1200 }); const cardJob = useQuery({ queryKey: ['job', cardJobId], queryFn: () => deckApi.getGenerationJob(cardJobId!), enabled: Boolean(cardJobId), refetchInterval: 1200 })
  const refresh = () => { queryClient.invalidateQueries({ queryKey: ['questions', topicId] }); queryClient.invalidateQueries({ queryKey: ['progress', topicId] }) }
  const generate = useMutation({ mutationFn: () => deckApi.generateQuestions(topicId!), onSuccess: (data) => setJobId(data.id), onError: (e: Error) => setError(e.message) }); const decide = useMutation({ mutationFn: ({ id, decision }: { id: string; decision: 'APPROVE' | 'REJECT' }) => deckApi.decideQuestion(id, decision), onSuccess: () => { refresh() }, onError: (e: Error) => setError(e.message) }); const bulk = useMutation({ mutationFn: (decision: 'APPROVE' | 'REJECT') => deckApi.decideQuestions(selected, decision), onSuccess: () => { setSelected([]); refresh() }, onError: (e: Error) => setError(e.message) }); const makeCards = useMutation({ mutationFn: async () => { if (selected.length) await deckApi.decideQuestions(selected, 'APPROVE'); return deckApi.generateCards(topicId!) }, onSuccess: (data) => { setSelected([]); refresh(); setCardJobId(data.id) }, onError: (e: Error) => setError(e.message) })
  useEffect(() => { if (job.data?.status === 'READY') { setJobId(undefined); refresh() } if (job.data?.status === 'ERROR') setError(job.data.errorMessage || 'Не удалось создать вопросы.') }, [job.data?.status])
  useEffect(() => { if (cardJob.data?.status === 'READY') { setCardJobId(undefined); queryClient.invalidateQueries({ queryKey: ['cards', topicId] }); queryClient.invalidateQueries({ queryKey: ['progress', topicId] }) } if (cardJob.data?.status === 'ERROR') setError(cardJob.data.errorMessage || 'Не удалось создать карточки.') }, [cardJob.data?.status])
  if (questions.isLoading) return <InlineLoading />; if (questions.isError) return <ErrorState onRetry={() => questions.refetch()} />
  const all = questions.data || []; const pending = all.filter((item) => item.status === 'GENERATED'); const approved = all.filter((item) => item.status === 'APPROVED'); const current = pending[index % Math.max(pending.length, 1)]; const processingQuestions = generate.isPending || Boolean(jobId); const processingCards = makeCards.isPending || Boolean(cardJobId)
  return <section className="topic-section"><div className="section-heading"><div><h2>Вопросы</h2><p className="muted">Оставьте только то, что действительно хотите помнить.</p></div><div className="heading-actions"><button className={view === 'review' ? 'segmented active' : 'segmented'} onClick={() => setView('review')}>По одному</button><button className={view === 'list' ? 'segmented active' : 'segmented'} onClick={() => setView('list')}>Списком</button></div></div>{error && <InlineError message={error} />}{!all.length && !processingQuestions ? <EmptyState icon={<Sparkles size={24} />} title="Вопросов пока нет" text="Когда материалы будут готовы, запустите генерацию вопросов." action={<button className="button button-primary" onClick={() => generate.mutate()}><Sparkles size={17} /> Создать вопросы</button>} /> : processingQuestions ? <ProcessingCard title="Анализируем материалы" subtitle="Создаём вопросы по единому тексту…" count={job.data?.itemsCreated} /> : view === 'review' ? <QuestionReview pending={pending} current={current} index={index} onDecide={(decision) => current && decide.mutate({ id: current.id, decision })} /> : <QuestionList questions={all} selected={selected} setSelected={setSelected} />}{all.length > 0 && !processingQuestions && <div className="question-footer"><div><strong>{approved.length}</strong> {plural(approved.length, 'вопрос выбран', 'вопроса выбрано', 'вопросов выбрано')}</div><div className="footer-actions"><button className="button button-secondary" disabled={!selected.length || bulk.isPending} onClick={() => bulk.mutate('REJECT')}>Снять выбор</button><button className="button button-primary" disabled={(!approved.length && !selected.length) || processingCards} onClick={() => makeCards.mutate()}>{processingCards ? 'Создаём карточки…' : <>Создать карточки <ChevronRight size={16} /></>}</button></div></div>}{processingCards && <ProcessingCard title="Создаём карточки" subtitle="Превращаем выбранные вопросы в карточки…" count={cardJob.data?.itemsCreated} />}{approved.length > 0 && !processingCards && <div className="success-banner"><div className="success-icon"><Check size={18} /></div><div><strong>{approved.length} {plural(approved.length, 'карточка готова', 'карточки готовы', 'карточек готовы')}</strong><p className="muted">Можно начать обучение прямо сейчас.</p></div><button className="button button-dark" onClick={() => navigate('../learn')}>Начать обучение <Play size={15} fill="currentColor" /></button></div>}{!all.length && !processingQuestions && <button className="text-button centered-action" onClick={() => generate.mutate()}><Sparkles size={15} /> Создать вопросы</button>}</section>
}

function QuestionReview({ pending, current, index, onDecide }: { pending: Question[]; current?: Question; index: number; onDecide: (decision: 'APPROVE' | 'REJECT') => void }) { if (!current) return <EmptyState icon={<Check size={24} />} title="Все вопросы просмотрены" text="Выберите вопросы в списке или создайте карточки из одобренных." />; return <div className="review-panel"><div className="review-count">{Math.min(index + 1, pending.length)} <span>/ {pending.length}</span></div><div className="review-question"><div className="question-label">ВОПРОС</div><h3>{current.text}</h3>{current.sourceFragment && <details><summary>Источник</summary><p>{current.sourceFragment}</p></details>}</div><div className="review-actions"><button className="decision-button reject" onClick={() => onDecide('REJECT')}><X size={19} /> Не изучать</button><button className="decision-button approve" onClick={() => onDecide('APPROVE')}>Хочу изучить <Check size={19} /></button></div></div> }

function QuestionList({ questions, selected, setSelected }: { questions: Question[]; selected: string[]; setSelected: (ids: string[]) => void }) { const selectable = questions.filter((question) => question.status === 'GENERATED'); const allSelected = selectable.length > 0 && selectable.every((question) => selected.includes(question.id)); const toggle = (id: string) => setSelected(selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id]); return <div className="question-list"><div className="list-toolbar"><button className="text-button" onClick={() => setSelected(allSelected ? [] : selectable.map((item) => item.id))}>{allSelected ? 'Снять всё' : 'Выбрать всё'}</button><span className="muted">{selected.length} выбрано</span></div>{questions.filter((question) => question.status !== 'CARD_CREATED').map((question) => <label className={`question-item ${question.status !== 'GENERATED' ? 'is-disabled' : ''}`} key={question.id}><input type="checkbox" disabled={question.status !== 'GENERATED'} checked={selected.includes(question.id)} onChange={() => toggle(question.id)} /><span className="checkmark"><Check size={13} /></span><span className="question-item-text">{question.text}</span><span className={`question-status status-${question.status.toLowerCase()}`}>{questionStatusLabel(question.status)}</span></label>)}</div> }

function CardsPage() {
  const { topicId } = useParams(); const queryClient = useQueryClient(); const [search, setSearch] = useState(''); const [editing, setEditing] = useState<Flashcard>(); const query = useQuery({ queryKey: ['cards', topicId], queryFn: () => deckApi.listCards(topicId!), enabled: Boolean(topicId) }); const deleteMutation = useMutation({ mutationFn: deckApi.deleteCard, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['cards', topicId] }) }); const filtered = (query.data || []).filter((card) => `${card.front} ${card.back}`.toLowerCase().includes(search.toLowerCase()))
  if (query.isLoading) return <InlineLoading />; if (query.isError) return <ErrorState onRetry={() => query.refetch()} />
  return <section className="topic-section"><div className="section-heading"><div><h2>Карточки <span className="count-badge">{query.data?.length || 0}</span></h2><p className="muted">Открывайте ответ, редактируйте и возвращайтесь к сложному.</p></div></div>{query.data?.length ? <><div className="search-box"><Search size={17} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Поиск по карточкам" /></div>{filtered.length ? <div className="card-list">{filtered.map((card) => <FlashcardRow key={card.id} card={card} edit={() => setEditing(card)} remove={() => { if (window.confirm('Удалить карточку?')) deleteMutation.mutate(card.id) }} />)}</div> : <EmptyState title="Ничего не найдено" text="Попробуйте изменить поисковый запрос." />}</> : <EmptyState icon={<BookOpen size={24} />} title="Карточек пока нет" text="Одобрите вопросы и создайте из них первую колоду." />}{editing && <EditCardModal card={editing} close={() => setEditing(undefined)} />}</section>
}

function FlashcardRow({ card, edit, remove }: { card: Flashcard; edit: () => void; remove: () => void }) { const [open, setOpen] = useState(false); return <article className="flashcard-row"><button className="flashcard-main" onClick={() => setOpen(!open)}><span className="flashcard-front">{card.front}</span><span className="flashcard-chevron">{open ? '−' : '+'}</span>{open && <span className="flashcard-back">{card.back}</span>}</button><div className="row-actions"><button className="text-button" onClick={edit}>Изменить</button><button className="icon-button subtle" onClick={remove} title="Удалить"><Trash2 size={16} /></button></div></article> }

function EditCardModal({ card, close }: { card: Flashcard; close: () => void }) { const queryClient = useQueryClient(); const showToast = useToast((state) => state.show); const [front, setFront] = useState(card.front); const [back, setBack] = useState(card.back); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: () => deckApi.updateCard(card.id, { front: front.trim(), back: back.trim() }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['cards', card.topicId] }); showToast('Карточка сохранена'); close() }, onError: (e: Error) => setError(e.message) }); return <Modal title="Изменить карточку" close={close}>{error && <InlineError message={error} />}<div className="form-stack"><label>Вопрос<textarea value={front} onChange={(e) => setFront(e.target.value)} rows={4} maxLength={2000} /></label><label>Ответ<textarea value={back} onChange={(e) => setBack(e.target.value)} rows={7} maxLength={10000} /></label></div><div className="modal-actions"><button className="button button-secondary" onClick={close}>Отмена</button><button className="button button-primary" disabled={mutation.isPending || !front.trim() || !back.trim()} onClick={() => mutation.mutate()}>{mutation.isPending ? 'Сохраняем…' : 'Сохранить'}</button></div></Modal> }

function LearningPage() {
  const { topicId } = useParams(); const queryClient = useQueryClient(); const { session, queue, remembered, forgotten, setSession, record, reset } = useLearning(); const [ready, setReady] = useState(false); const [revealed, setRevealed] = useState(false); const [finished, setFinished] = useState(false); const [finalSession, setFinalSession] = useState(session); const start = useMutation({ mutationFn: () => learningApi.startLearningSession(topicId!), onSuccess: async (newSession) => { const cards = await queryClient.fetchQuery({ queryKey: ['due-cards', topicId], queryFn: () => learningApi.getDueCards(topicId!) }); setSession(newSession, cards); setReady(true) }, onError: () => setReady(true) }); const review = useMutation({ mutationFn: ({ card, result }: { card: DueCard; result: 'REMEMBER' | 'FORGOT' }) => learningApi.reviewCard(card.cardId, result, session?.id), onSuccess: (outcome, variables) => { record(outcome.result === 'REMEMBER', outcome.returnToSession ? variables.card : undefined); setRevealed(false); queryClient.invalidateQueries({ queryKey: ['progress', topicId] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }) } }); const complete = useMutation({ mutationFn: () => learningApi.completeLearningSession(session!.id), onSuccess: (result) => { setFinalSession(result); setFinished(true); queryClient.invalidateQueries({ queryKey: ['progress', topicId] }); queryClient.invalidateQueries({ queryKey: ['dashboard'] }) } })
  useEffect(() => { if (session && session.topicId !== topicId) { reset(); setReady(false); setFinished(false) } }, [topicId, session?.topicId])
  useEffect(() => { if (!session && !start.isPending && !ready) start.mutate() }, [session, ready])
  useEffect(() => { if (session && ready && !queue.length && !complete.isPending && !finished) complete.mutate() }, [queue.length, ready, session, finished])
  if (!ready || start.isPending) return <div className="learning-loading"><div className="spinner" /><p>Готовим карточки…</p></div>
  if (finished || complete.isSuccess) return <LearningComplete session={finalSession} remembered={remembered} forgotten={forgotten} reset={reset} />
  const card = queue[0]
  if (!card) return <EmptyState icon={<GraduationCap size={24} />} title="Пока нечего повторять" text="Когда появятся карточки к повторению, они будут ждать вас здесь." action={<Link className="button button-primary" to="..">Вернуться к теме</Link>} />
  return <div className="learning-page"><div className="learning-top"><Link to=".." className="back-link"><ChevronLeft size={17} /> К теме</Link><span className="learning-progress">{(session?.cardsTotal || 0) - queue.length + 1} / {session?.cardsTotal || queue.length}</span><span className="learning-topic">Обучение</span></div><div className="learning-card"><div className="learning-card-meta"><span>Этап {card.stage} из 6</span><span>{card.totalReviews ? `${card.totalReviews} повторений` : 'Новая карточка'}</span></div><div className="learning-card-body"><div className="question-label">ВОПРОС</div><h1>{card.front}</h1>{revealed && <div className="answer"><div className="answer-line" /><div className="question-label">ОТВЕТ</div><p>{card.back}</p></div>}</div>{!revealed ? <button className="button button-dark reveal-button" onClick={() => setRevealed(true)}>Показать ответ <ChevronRight size={17} /></button> : <div className="learning-actions"><button className="decision-button reject" disabled={review.isPending} onClick={() => review.mutate({ card, result: 'FORGOT' })}><X size={19} /> Не помню</button><button className="decision-button approve" disabled={review.isPending} onClick={() => review.mutate({ card, result: 'REMEMBER' })}>Помню <Check size={19} /></button></div>}</div></div>
}

function LearningComplete({ session, remembered, forgotten, reset }: { session?: { cardsRemembered: number; cardsForgotten: number }; remembered: number; forgotten: number; reset: () => void }) { return <div className="complete-page"><div className="complete-mark">✓</div><div className="eyebrow">Сессия завершена</div><h1>Готово 🎉</h1><p className="muted">Хорошая работа. Знания становятся крепче с каждым повторением.</p><div className="complete-stats"><Stat label="Пройдено" value={String((session?.cardsRemembered || 0) + (session?.cardsForgotten || 0) || remembered + forgotten)} /><Stat label="Помню" value={String(session?.cardsRemembered || remembered)} /><Stat label="Не помню" value={String(session?.cardsForgotten || forgotten)} /></div><div className="complete-actions"><Link className="button button-primary" to=".." onClick={reset}>На главную темы</Link><button className="button button-secondary" onClick={reset}>Закрыть</button></div></div> }

function ProgressPage() { const { topicId } = useParams(); const query = useQuery({ queryKey: ['progress', topicId], queryFn: () => learningApi.getTopicProgress(topicId!), enabled: Boolean(topicId) }); if (query.isLoading) return <InlineLoading />; if (query.isError || !query.data) return <ErrorState onRetry={() => query.refetch()} />; const data = query.data; return <section className="topic-section"><div className="section-heading"><div><h2>Прогресс</h2><p className="muted">Понятная картина того, что уже закрепилось.</p></div></div><div className="progress-overview"><div className="big-progress"><div className="ring" style={{ '--progress': `${data.progress}%` } as React.CSSProperties}><strong>{formatPercent(data.progress)}</strong></div><div><div className="eyebrow">Общий прогресс</div><h3>{data.masteredCards} из {data.totalCards} карточек изучено</h3><p className="muted">Изученной считается карточка, которая прошла все этапы повторения.</p></div></div><div className="progress-bars"><ProgressLine label="Изучено" value={data.masteredCards} total={data.totalCards} color="green" /><ProgressLine label="На изучении" value={data.learningCards} total={data.totalCards} color="orange" /><ProgressLine label="Новые" value={data.newCards} total={data.totalCards} color="gray" /></div></div><div className="progress-grid"><StatCard label="Всего карточек" value={data.totalCards} /><StatCard label="Повторить сейчас" value={data.dueCards} accent /><StatCard label="До конца сегодня" value={data.dueToday} /></div></section> }
function ProgressLine({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { return <div className="progress-line"><div><span>{label}</span><strong>{value}</strong></div><div className="progress-track"><span className={`bar-${color}`} style={{ width: `${total ? (value / total) * 100 : 0}%` }} /></div></div> }
function StatCard({ label, value, accent = false }: { label: string; value: number; accent?: boolean }) { return <div className="stat-card"><span className="muted small">{label}</span><strong className={accent ? 'accent-text' : ''}>{value}</strong></div> }

function EditTopicModal({ topic, close }: { topic: Topic; close: () => void }) { const navigate = useNavigate(); const queryClient = useQueryClient(); const [title, setTitle] = useState(topic.title); const [description, setDescription] = useState(topic.description || ''); const [error, setError] = useState(''); const update = useMutation({ mutationFn: () => topicsApi.updateTopic(topic.id, { title: title.trim(), description: description.trim() }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['topic', topic.id] }); queryClient.invalidateQueries({ queryKey: ['topics'] }); close() }, onError: (e: Error) => setError(e.message) }); const remove = useMutation({ mutationFn: () => topicsApi.deleteTopic(topic.id), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['topics'] }); navigate('/'); close() } }); return <Modal title="Настройки темы" close={close}>{error && <InlineError message={error} />}<div className="form-stack"><label>Название<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><label>Описание<textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={4} /></label></div><div className="modal-danger"><button className="text-button danger" disabled={remove.isPending} onClick={() => window.confirm('Удалить тему вместе с материалами и карточками?') && remove.mutate()}><Trash2 size={15} /> Удалить тему</button></div><div className="modal-actions"><button className="button button-secondary" onClick={close}>Отмена</button><button className="button button-primary" disabled={update.isPending || !title.trim()} onClick={() => update.mutate()}>{update.isPending ? 'Сохраняем…' : 'Сохранить'}</button></div></Modal> }

function Modal({ title, close, children, wide = false }: { title: string; close: () => void; children: React.ReactNode; wide?: boolean }) { return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) close() }}><div className={`modal ${wide ? 'modal-wide' : ''}`} role="dialog" aria-modal="true"><div className="modal-header"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Закрыть"><X size={19} /></button></div>{children}</div></div> }
function ToastContainer() { const { toast, clear } = useToast(); useEffect(() => { if (!toast) return undefined; const timer = window.setTimeout(clear, 3200); return () => window.clearTimeout(timer) }, [toast, clear]); return toast ? <div className={`toast toast-${toast.tone}`} role="status"><Check size={16} /> {toast.message}</div> : null }
function PageLoading() { return <div className="page-loader"><div className="spinner" /> Загружаем…</div> }
function InlineLoading() { return <div className="inline-loading"><div className="spinner small-spinner" /> Загружаем…</div> }
function ProcessingCard({ title, subtitle, count }: { title: string; subtitle: string; count?: number }) { return <div className="processing-card"><div className="processing-orb"><Sparkles size={21} /></div><div><h3>{title}<span className="ellipsis">…</span></h3><p className="muted">{subtitle}</p></div>{typeof count === 'number' && <strong className="processing-count">{count}</strong>}<div className="processing-line" /></div> }
function EmptyState({ icon, title, text, action }: { icon?: React.ReactNode; title: string; text: string; action?: React.ReactNode }) { return <div className="empty-state">{icon && <div className="empty-icon">{icon}</div>}<h3>{title}</h3><p className="muted">{text}</p>{action}</div> }
function ErrorState({ message = 'Не удалось загрузить данные.', onRetry }: { message?: string; onRetry?: () => void }) { return <div className="empty-state error-state"><div className="empty-icon">!</div><h3>Что-то пошло не так</h3><p className="muted">{message}</p>{onRetry && <button className="button button-secondary" onClick={onRetry}>Попробовать снова</button>}</div> }
function InlineError({ message }: { message: string }) { return <div className="inline-error">{message}</div> }
function statusLabel(status: string) { return ({ DRAFT: 'Черновик', PROCESSING: 'Обрабатывается', READY: 'Готово', ERROR: 'Ошибка' } as Record<string, string>)[status] || status }
function sourceTypeLabel(type: string) { return ({ PDF: 'PDF-документ', YOUTUBE: 'Видео YouTube', TEXT: 'Текстовые заметки', WORD_LIST: 'Список слов' } as Record<string, string>)[type] || type }
function questionStatusLabel(status: string) { return ({ GENERATED: 'Новый', APPROVED: 'Выбран', REJECTED: 'Пропущен', CARD_CREATED: 'В карточках' } as Record<string, string>)[status] || status }
