package net.pamytno.topic.integration.youtube;

import java.util.Comparator;
import java.util.List;
import java.util.Optional;

/**
 * Выбирает дорожку субтитров: сначала ручные в предпочтительных языках, затем автоматические
 * в предпочтительных языках, затем любые ручные, затем любые.
 */
public final class CaptionTrackSelector {

    private static final int OTHER_LANGUAGE_RANK = 1000;

    /**
     * Запрещает создание экземпляров.
     */
    private CaptionTrackSelector() {
    }

    /**
     * Выбирает лучшую дорожку.
     *
     * @param tracks             доступные дорожки
     * @param preferredLanguages языки в порядке предпочтения
     * @return выбранная дорожка, если хоть одна есть
     */
    public static Optional<CaptionTrack> select(List<CaptionTrack> tracks, List<String> preferredLanguages) {
        Comparator<CaptionTrack> byPreference = Comparator
                .comparingInt((CaptionTrack track) -> isPreferred(track, preferredLanguages) ? 0 : 1)
                .thenComparing(CaptionTrack::autoGenerated)
                .thenComparingInt(track -> languageRank(track, preferredLanguages));
        return tracks.stream().min(byPreference);
    }

    /**
     * Проверяет, что язык дорожки в списке предпочтительных.
     *
     * @param track              дорожка
     * @param preferredLanguages предпочтительные языки
     * @return {@code true}, если язык предпочтительный
     */
    private static boolean isPreferred(CaptionTrack track, List<String> preferredLanguages) {
        return languageRank(track, preferredLanguages) < OTHER_LANGUAGE_RANK;
    }

    /**
     * Позиция языка дорожки в списке предпочтений.
     *
     * @param track              дорожка
     * @param preferredLanguages предпочтительные языки
     * @return индекс языка или большое число, если язык не в списке
     */
    private static int languageRank(CaptionTrack track, List<String> preferredLanguages) {
        var index = preferredLanguages.indexOf(track.languageCode());
        return index < 0 ? OTHER_LANGUAGE_RANK : index;
    }
}
