package net.pamytno.topic.integration.youtube;

/**
 * Дорожка субтитров видео.
 *
 * @param languageCode  код языка, например {@code ru}
 * @param baseUrl       адрес XML с субтитрами
 * @param autoGenerated {@code true} для автоматически распознанных субтитров
 */
public record CaptionTrack(String languageCode, String baseUrl, boolean autoGenerated) {
}
