/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/topics/{topicId}/reviews/due": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** Карточки темы, которые пора повторить */
        get: operations["getDueReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{cardId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ответ пользователя по карточке
         * @description REMEMBER — вспомнил, карточка переходит на следующий этап. FORGOT — не вспомнил, этап уменьшается, карточка возвращается в текущую сессию. CONTINUE — не оценка памяти, прогресс не меняется.
         */
        post: operations["reviewCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/learning-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Начать учебную сессию по теме */
        post: operations["startLearningSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        /** Учебная сессия */
        get: operations["getLearningSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/learning-sessions/{sessionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Завершить учебную сессию */
        post: operations["completeLearningSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics/{topicId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** Прогресс изучения темы */
        get: operations["getTopicProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Общий прогресс пользователя по всем темам */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ReviewResult: "REMEMBER" | "FORGOT" | "CONTINUE";
        ReviewRequest: {
            result: components["schemas"]["ReviewResult"];
            /**
             * Format: uuid
             * @description Текущая учебная сессия — для статистики
             */
            sessionId?: string;
        };
        DueCardDto: {
            /** Format: uuid */
            cardId: string;
            /** Format: uuid */
            topicId: string;
            front: string;
            back: string;
            /** @description Этап повторения 0–5; 6 — карточка изучена */
            stage: number;
            /** Format: date-time */
            nextReviewAt?: string;
            totalReviews: number;
        };
        ReviewResultDto: {
            /** Format: uuid */
            cardId: string;
            result: components["schemas"]["ReviewResult"];
            stage: number;
            /**
             * Format: date-time
             * @description Когда повторить; пусто, если карточка изучена
             */
            nextReviewAt?: string;
            mastered: boolean;
            /** @description Показать карточку ещё раз в текущей сессии (после FORGOT) */
            returnToSession: boolean;
        };
        LearningSessionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt?: string;
            cardsTotal: number;
            cardsRemembered: number;
            cardsForgotten: number;
        };
        TopicProgressDto: {
            /** Format: uuid */
            topicId: string;
            totalCards: number;
            /** @description Ни разу не повторялись */
            newCards: number;
            /** @description На изучении — повторялись, но ещё не изучены */
            learningCards: number;
            /** @description Изучены (прошли этап 5) */
            masteredCards: number;
            /** @description Ожидают повторения прямо сейчас */
            dueCards: number;
            /** @description К повторению до конца сегодняшнего дня */
            dueToday: number;
            /**
             * Format: double
             * @description Процент изученных карточек, 0–100 с одним знаком после запятой
             */
            progress: number;
        };
        DashboardDto: {
            totalCards: number;
            newCards: number;
            learningCards: number;
            masteredCards: number;
            dueCards: number;
            dueToday: number;
            /** Format: double */
            progress: number;
            topics: components["schemas"]["TopicProgressDto"][];
        };
        ErrorResponse: {
            code: string;
            message: string;
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: {
        /** @description Некорректный запрос (VALIDATION_FAILED, MALFORMED_REQUEST) */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Нет валидного токена (UNAUTHORIZED) */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не найдено (LEARNING_SESSION_NOT_FOUND) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        TopicId: string;
        SessionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDueReviews: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Карточки, срок повторения которых наступил, — самые давние первыми */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DueCardDto"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    reviewCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Новое состояние карточки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResultDto"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Прогресса карточки нет (CARD_PROGRESS_NOT_FOUND) или сессия не найдена (LEARNING_SESSION_NOT_FOUND) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Сессия завершена (LEARNING_SESSION_COMPLETED) или относится к другой теме (LEARNING_SESSION_TOPIC_MISMATCH) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startLearningSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия начата; cardsTotal — сколько карточек к повторению на старте */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getLearningSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    completeLearningSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Завершённая сессия */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningSessionDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getTopicProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Прогресс темы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicProgressDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Итоги и прогресс каждой темы с карточками */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardDto"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
