package net.pamytno.topic.integration.youtube;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit-тесты {@link CaptionTrackSelector}.
 */
class CaptionTrackSelectorTest {

    private static final List<String> PREFERRED = List.of("ru", "en");
    private static final CaptionTrack RU_AUTO = new CaptionTrack("ru", "ru-auto", true);
    private static final CaptionTrack EN_MANUAL = new CaptionTrack("en", "en-manual", false);
    private static final CaptionTrack RU_MANUAL = new CaptionTrack("ru", "ru-manual", false);
    private static final CaptionTrack DE_MANUAL = new CaptionTrack("de", "de-manual", false);

    @Test
    @DisplayName("Ручные субтитры предпочтительного языка важнее всех остальных")
    void select_prefersManualTrackInFirstLanguage() {
        assertThat(CaptionTrackSelector.select(List.of(DE_MANUAL, RU_AUTO, EN_MANUAL, RU_MANUAL), PREFERRED))
                .contains(RU_MANUAL);
    }

    @Test
    @DisplayName("Ручные субтитры второго языка важнее автоматических первого")
    void select_prefersManualOverAutoGenerated() {
        assertThat(CaptionTrackSelector.select(List.of(RU_AUTO, EN_MANUAL), PREFERRED)).contains(EN_MANUAL);
    }

    @Test
    @DisplayName("Любой предпочтительный язык важнее непредпочтительного")
    void select_prefersPreferredLanguage() {
        assertThat(CaptionTrackSelector.select(List.of(DE_MANUAL, RU_AUTO), PREFERRED)).contains(RU_AUTO);
    }

    @Test
    @DisplayName("Если предпочтительных нет, берётся любая дорожка; без дорожек — пусто")
    void select_fallsBackToAnyTrack() {
        assertThat(CaptionTrackSelector.select(List.of(DE_MANUAL), PREFERRED)).contains(DE_MANUAL);
        assertThat(CaptionTrackSelector.select(List.of(), PREFERRED)).isEmpty();
    }
}
